### ISSUE TITLE
missing rainbow as dependency

### ISSUE THREAD

**Issue by Poil** [ncamacho/gitlab_clone#3]
Hi

When installing the gem it's not installing rainbow that's required for the help

```
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rainbow (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/gitlab_clone-0.12.1/lib/setup.rb:2:in `<class:Setup>'
	from /var/lib/gems/2.3.0/gems/gitlab_clone-0.12.1/lib/setup.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/gitlab_clone-0.12.1/lib/gitlab.rb:2:in `<class:Gitlab>'
	from /var/lib/gems/2.3.0/gems/gitlab_clone-0.12.1/lib/gitlab.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/gitlab_clone-0.12.1/bin/gitlab-clone:7:in `<top (required)>'
	from /usr/local/bin/gitlab-clone:23:in `load'
	from /usr/local/bin/gitlab-clone:23:in `<main>'
```

**Comment by ncamacho** [comment]
Fixed in version v13.0
